image: python

stages:
  - production

production:
  type: deploy
  stage: production
  before_script:
    - mkdir -p ~/.ssh
    - echo -e "$SSH_PRIVATE" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" >  ~/.ssh/config'
    
  script:
  - bash deploy.sh   
  only:
    - main
